use voker_reflect_derive::impl_reflect_opaque;

impl_reflect_opaque!(::voker_utils::num::NonMaxI128(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::voker_utils::num::NonMaxU128(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::voker_utils::num::NonMaxIsize(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::voker_utils::num::NonMaxUsize(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::voker_utils::num::NonMaxI64(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::voker_utils::num::NonMaxU64(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::voker_utils::num::NonMaxU32(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::voker_utils::num::NonMaxI32(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::voker_utils::num::NonMaxI16(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::voker_utils::num::NonMaxU16(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::voker_utils::num::NonMaxU8(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::voker_utils::num::NonMaxI8(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
