use crate::derive::impl_reflect_opaque;

impl_reflect_opaque!(::core::num::NonZeroI128(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::NonZeroU128(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::NonZeroIsize(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::NonZeroUsize(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::NonZeroI64(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::NonZeroU64(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::NonZeroU32(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::NonZeroI32(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::NonZeroI16(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::NonZeroU16(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::NonZeroU8(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::NonZeroI8(
    Debug,
    Clone,
    Hash,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize
));
impl_reflect_opaque!(::core::num::Wrapping<T: Clone + Send + Sync>(Clone));
impl_reflect_opaque!(::core::num::Saturating<T: Clone + Send + Sync>(Clone));
